version: "2.1"

services:
    app:
        build: .
        env_file:
            - local.env
        ports:
            - 8000:8000
        depends_on:
            - rabbitmq
            - pg

    pg:
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data

    rabbitmq:
        image: rabbitmq:3-management
        environment:
        - RABBITMQ_PASSWORD=guest
        - RABBITMQ_USERNAME=guest

        ports:
        - 5672:5672
        - 15672:15672
